// Generated by janux-vercel. Do not edit — it is rewritten on every deployment build.
import { join } from 'node:path';
import type { VercelApp } from '@janux/vercel';
import * as m0 from '../src/routes/index';
import * as m1 from '../src/agent';

/** The app root, from the bundle's own location: `.janux/server.js` → the app. */
const root = join(import.meta.dir, '..');
const path = (file: string) => join(root, file);

const app: VercelApp = {
  root,
  config: {
    root,
    routesDir: path("src/routes"),
    serverDir: path("src/server"),
    clientEntry: path("../../../../.."),
    agentModule: path("src/agent.ts"),
    title: "Fixture",
    output: "bun",
  },
  modules: {
    [path("src/routes/index.tsx")]: m0,
    [path("src/agent.ts")]: m1,
  },
};

export default app;
