import { existsSync, readdirSync, statSync } from 'node:fs';
import { join, relative } from 'node:path';
import { createFsRouter } from '@janux/server';
import { apiFiles, type JanuxAppConfig } from '@janux/vite/config';

/**
 * The app, resolved at build time into a module a bundler can see through.
 *
 * A Janux server imports the app's own source when it boots, which a bundled
 * function cannot do: there is no `node_modules` beside it to resolve `janux`
 * from, and the first import — `janux.config.ts` — fails. So the deployment
 * ships a generated module that imports every one of those files *statically*
 * (the bundler inlines them) and hands them to `prodServerOptions` as a
 * prebuilt app. Paths are rebuilt from the module's own location, because the
 * build machine's absolute paths are not the runtime's.
 */

/** Config fields that are filesystem paths, and therefore have to be rebuilt at runtime. */
const PATH_FIELDS = new Set([
  'routesDir',
  'serverDir',
  'clientEntry',
  'agentModule',
  'storesModule',
  'i18nModule',
  'middlewareModule',
  'ctxModule',
  'matchersModule',
  'websocketModule',
  'httpHandlersDir',
  'stylesheet',
]);

function walkFiles(dir: string): string[] {
  return readdirSync(dir).flatMap((entry) => {
    const path = join(dir, entry);

    return statSync(path).isDirectory() ? walkFiles(path) : [path];
  });
}

/** Every module the server imports on the way up: routes, layouts, apis, and the conventional singles. */
export function appModules(app: JanuxAppConfig): string[] {
  // An app with no routes yet is a legitimate state for the command to run in.
  const router = existsSync(app.routesDir) ? createFsRouter(app.routesDir) : undefined;
  const found = router?.routes ?? [];
  // `_404`/`_500` are pages no URL matches, so the route list never mentions
  // them — and a bundled function that cannot import them has no error pages.
  const errorPages = Object.values(router?.errorPages ?? {});
  const routes = [...found.flatMap((route) => [route.filePath, ...route.layouts]), ...errorPages];
  const singles = [
    app.agentModule,
    app.storesModule,
    app.i18nModule,
    app.middlewareModule,
    app.ctxModule,
    app.matchersModule,
    app.websocketModule,
  ];
  const handlers = app.httpHandlersDir ? walkFiles(app.httpHandlersDir) : [];

  return [...new Set([...routes, ...apiFiles(app.serverDir), ...handlers, ...singles].filter(Boolean) as string[])];
}

/** `'/app/src/routes/index.tsx'` → `path('src/routes/index.tsx')`, evaluated at runtime. */
function pathExpression(root: string, file: string): string {
  return `path(${JSON.stringify(relative(root, file))})`;
}

function configEntries(root: string, app: JanuxAppConfig): string[] {
  return Object.entries(app)
    .filter(([, value]) => value !== undefined)
    .map(([key, value]) =>
      key === 'root'
        ? '    root,'
        : `    ${key}: ${PATH_FIELDS.has(key) ? pathExpression(root, value as string) : JSON.stringify(value)},`,
    );
}

/** Extensionless: TypeScript rejects a `.ts` specifier unless the app opted into them. */
function importSpecifier(root: string, file: string): string {
  return `../${relative(root, file).replace(/\.[jt]sx?$/, '')}`;
}

export function generateApp(root: string, app: JanuxAppConfig, adapter = 'the Janux adapter'): string {
  const files = appModules(app);
  const imports = files.map((file, index) => `import * as m${index} from '${importSpecifier(root, file)}';`);
  const modules = files.map((file, index) => `  [${pathExpression(root, file)}]: m${index},`);

  return [
    `// Generated by ${adapter}. Do not edit — it is rewritten on every deployment build.`,
    "import { join } from 'node:path';",
    "import type { JanuxApp } from '@janux/cli/adapter';",
    ...imports,
    '',
    "/** The app root, from the bundle's own location: `.janux/server.js` → the app. */",
    "const root = join(import.meta.dirname, '..');",
    'const path = (file: string) => join(root, file);',
    '',
    'const app: JanuxApp = {',
    '  root,',
    '  config: {',
    ...configEntries(root, app),
    '  },',
    '  modules: {',
    ...modules.map((line) => `  ${line}`),
    '  },',
    '};',
    '',
    'export default app;',
    '',
  ].join('\n');
}
