import { describe, expect, it } from 'bun:test';
import { existsSync, mkdirSync, mkdtempSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { resolveAppConfig } from '@janux/vite/config';
import { appModules, generateApp } from './adapter-generate';
import { bundlerPath } from './adapter-build';

const APP = join(import.meta.dirname, '__fixtures__/adapter-app');

describe('appModules', () => {
  it('lists the app modules the server would import on the way up', async () => {
    const app = await resolveAppConfig(APP);

    expect(appModules(app)).toEqual([join(APP, 'src/routes/index.tsx')]);
  });

  /** No URL matches `_404`/`_500`, so the route list never names them — and a bundle without them has no error pages. */
  it('includes the error pages', async () => {
    const root = mkdtempSync(join(tmpdir(), 'janux-adapter-errors-'));

    mkdirSync(join(root, 'src/routes'), { recursive: true });
    ['index.tsx', '_404.tsx', '_500.tsx'].forEach((file) =>
      writeFileSync(join(root, 'src/routes', file), 'export default () => null;'),
    );

    expect(appModules(await resolveAppConfig(root))).toEqual([
      join(root, 'src/routes/index.tsx'),
      join(root, 'src/routes/_404.tsx'),
      join(root, 'src/routes/_500.tsx'),
    ]);
  });
});

describe('generateApp', () => {
  it('imports every module statically, so a bundler can see through it', async () => {
    const source = generateApp(APP, await resolveAppConfig(APP));

    expect(source).toContain("import * as m0 from '../src/routes/index';");
    expect(source).toContain('[path("src/routes/index.tsx")]: m0,');
  });

  /** The build machine's absolute paths are not the runtime's — every path is rebuilt from `root`. */
  it('rebuilds paths from the running location, and never hardcodes the build root', async () => {
    const source = generateApp(APP, await resolveAppConfig(APP));

    expect(source).toContain("const root = join(import.meta.dirname, '..');");
    expect(source).toContain('routesDir: path("src/routes")');
    expect(source).not.toContain(APP);
  });

  /** Adapters share the generator, so the file has to say which one wrote it. */
  it('names the adapter that generated it', async () => {
    expect(generateApp(APP, await resolveAppConfig(APP), '@janux/node')).toContain('Generated by @janux/node');
  });
});

/**
 * `src/ws.ts` was the one conventional module the generator forgot, on both
 * counts: it was not in the module map, and its path was emitted as the build
 * machine's. It went unnoticed because the only adapter that existed could not
 * hold a socket open anyway — `@janux/node` can, and declares that it does.
 */
describe('generateApp — the WebSocket module', () => {
  function appWithWs(): string {
    const root = mkdtempSync(join(tmpdir(), 'janux-adapter-ws-'));

    mkdirSync(join(root, 'src/routes'), { recursive: true });
    writeFileSync(join(root, 'src/routes/index.tsx'), 'export default () => null;');
    writeFileSync(join(root, 'src/ws.ts'), "export default { path: '/ws' };\n");

    return root;
  }

  it('is one of the modules the bundle inlines', async () => {
    const root = appWithWs();

    expect(appModules(await resolveAppConfig(root))).toContain(join(root, 'src/ws.ts'));
  });

  it('has its path rebuilt at runtime, not frozen to the build machine', async () => {
    const root = appWithWs();
    const source = generateApp(root, await resolveAppConfig(root));

    expect(source).toContain('websocketModule: path("src/ws.ts")');
    expect(source).not.toContain(root);
  });
});

describe('bundlerPath', () => {
  /**
   * The bundler is spawned as a sibling file, and what that sibling is called
   * depends on where the package is running from: `bundler.ts` in the workspace,
   * `bundler.js` once the package is compiled into `dist/`. Naming one of them
   * outright is a build that works here and breaks the moment it is published.
   */
  it('points at a file that exists next to this module', () => {
    const found = bundlerPath();

    expect(existsSync(found)).toBe(true);
    expect(found).toBe(join(import.meta.dirname, 'bundler.ts'));
  });

  it('accepts the compiled name too', () => {
    expect(bundlerPath((path) => path.endsWith('bundler.js'))).toBe(join(import.meta.dirname, 'bundler.js'));
  });

  it('says so when neither is there', () => {
    expect(() => bundlerPath(() => false)).toThrow(/bundler/);
  });
});
