#!/usr/bin/env bun
/**
 * Writes STABILITY.md from the runtime exports themselves.
 *
 * Nothing here decides what is public: `surface()` does, out of the modules
 * `public-api.ts` imports. This file only renders it, which is why the
 * document can be regenerated and byte-compared in the suite — a stability
 * contract that drifts from the code is worse than none.
 */
import { fileURLToPath } from 'node:url';
import { EXPERIMENTAL, surface, type Moving, type Tier } from './stability';

type Api = ReturnType<typeof surface>;

const PREAMBLE = `<!-- Generated by \`bun run docs:stability\`. Do not edit by hand: \`packages/docs-tests/stability.test.ts\`
     regenerates this file from the runtime exports and fails on any difference. -->

# Stability

Janux is 0.x. [VERSIONING.md](./VERSIONING.md) says what that costs you in general; this file says it per API.

Every runtime export of every published entry point appears below exactly once, and the list is not maintained by
hand — it is read from the modules themselves by the same code that asserts the reference docs cover them
(\`packages/docs-tests\`). An export that exists is on this page; a name on this page is a real export.

Type-only exports are outside this contract. They are documented, and they move, with the values that carry them.`;

const TIERS: readonly Tier[] = ['stable', 'experimental', 'internal'];
const HEADINGS: Record<Tier, string> = { stable: 'Stable', experimental: 'Experimental', internal: 'Internal' };
const PROMISE: Record<Tier, string> = {
  stable:
    'Breaks only on a minor, and only after a release that deprecates it in the changelog and warns at runtime where it can. This is the default: an export that nobody classified is a promise.',
  experimental:
    'Can break on any minor, no deprecation period. Still documented, still tested, still supported when it breaks — but building on it means reading the changelog before you upgrade.',
  internal:
    'No promise at all. Documented because embedding Janux in another build, driving it from a test or writing devtools needs it — not because an app should call it. Can change on a patch.',
};

function names(api: Api, entry: string, tier: Tier): string {
  const matching = api.filter((one) => one.entry === entry && one.tier === tier);

  return matching.length === 0 ? '_none_' : matching.map((one) => `\`${one.name}\``).join(', ');
}

function entrySection(api: Api, entry: string): string {
  const lines = TIERS.map((tier) => `- **${HEADINGS[tier]}** — ${names(api, entry, tier)}`);

  return [`### \`${entry}\``, '', ...lines].join('\n');
}

/** The APIs a single reason covers, named the way the reader will look for them. */
function covered(moving: Moving): string {
  const entries = (moving.entries ?? []).map((entry) => `\`${entry}\``);

  return [...entries, ...(moving.names ?? []).map((name) => `\`${name}()\``)].join(', ');
}

function tierTable(): string {
  const rows = TIERS.map((tier) => `| **${HEADINGS[tier]}** | ${PROMISE[tier]} |`);

  return ['| Tier | What it means for you |', '|---|---|', ...rows].join('\n');
}

function reasons(): string {
  const blocks = EXPERIMENTAL.map((moving) => `**${covered(moving)}** — ${moving.reason}`);

  return ['## Why these are experimental', '', blocks.join('\n\n')].join('\n');
}

/** `surface()` reads every reference page per name, so it is walked once and passed down. */
export function stabilityDocument(): string {
  const api = surface();
  const entries = [...new Set(api.map((one) => one.entry))].map((entry) => entrySection(api, entry));

  return `${[PREAMBLE, '## What the tiers mean', tierTable(), '## The surface', ...entries, reasons()].join('\n\n')}\n`;
}

if (import.meta.main) {
  // fileURLToPath, not `.pathname`: on Windows the pathname is `/C:/...`.
  const path = fileURLToPath(new URL('../../STABILITY.md', import.meta.url));
  const api = surface();

  await Bun.write(path, stabilityDocument());
  console.log(`✔ wrote ${path} — ${api.length} exports across ${new Set(api.map((one) => one.entry)).size} entry points`);
}
